config/routes.rb
Rails.application.routes.draw do

  resources :image_assets
  resources :tags
  resources :companies

  root "pages#index"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/image_asset.rb
class ImageAsset < ApplicationRecord
  has_many_attached :uploads
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :authenticate_user!

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website, :address, :city, :state, :zip, :phone, :Facebook_URL, :LinkedIn_URL, :Google_A_ID, :Instagram_URL, :Twitter_URL)
    end
end

app/controllers/image_assets_controller.rb
class ImageAssetsController < ApplicationController
  before_action :set_image_asset, only: [:show, :edit, :update, :destroy]

  # GET /image_assets
  # GET /image_assets.json
  def index
    @image_assets = ImageAsset.all
  end

  # GET /image_assets/1
  # GET /image_assets/1.json
  def show
  end

  # GET /image_assets/new
  def new
    @image_asset = ImageAsset.new
  end

  # GET /image_assets/1/edit
  def edit
  end

  # POST /image_assets
  # POST /image_assets.json
  def create
    @image_asset = ImageAsset.new(image_asset_params)

    respond_to do |format|
      if @image_asset.save
        format.html { redirect_to @image_asset, notice: 'Image asset was successfully created.' }
        format.json { render :show, status: :created, location: @image_asset }
      else
        format.html { render :new }
        format.json { render json: @image_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_assets/1
  # PATCH/PUT /image_assets/1.json
  def update
    respond_to do |format|
      if @image_asset.update(image_asset_params)
        format.html { redirect_to @image_asset, notice: 'Image asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_asset }
      else
        format.html { render :edit }
        format.json { render json: @image_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_assets/1
  # DELETE /image_assets/1.json
  def destroy
    @image_asset.destroy
    respond_to do |format|
      format.html { redirect_to image_assets_url, notice: 'Image asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_asset
      @image_asset = ImageAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_asset_params
      params.require(:image_asset).permit(:name, :description, :approval, :category, uploads: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :slug, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/image_assets_helper.rb
module ImageAssetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :Facebook_URL %>
    <%= form.text_field :Facebook_URL %>
  </div>

  <div class="field">
    <%= form.label :LinkedIn_URL %>
    <%= form.text_field :LinkedIn_URL %>
  </div>

  <div class="field">
    <%= form.label :Google_A_ID %>
    <%= form.text_field :Google_A_ID %>
  </div>

  <div class="field">
    <%= form.label :Instagram_URL %>
    <%= form.text_field :Instagram_URL %>
  </div>

  <div class="field">
    <%= form.label :Twitter_URL %>
    <%= form.text_field :Twitter_URL %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Facebook url</th>
      <th>Linkedin url</th>
      <th>Google a id</th>
      <th>Instagram url</th>
      <th>Twitter url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.address %></td>
        <td><%= company.city %></td>
        <td><%= company.state %></td>
        <td><%= company.zip %></td>
        <td><%= company.phone %></td>
        <td><%= company.Facebook_URL %></td>
        <td><%= company.LinkedIn_URL %></td>
        <td><%= company.Google_A_ID %></td>
        <td><%= company.Instagram_URL %></td>
        <td><%= company.Twitter_URL %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @company.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @company.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Facebook url:</strong>
  <%= @company.Facebook_URL %>
</p>

<p>
  <strong>Linkedin url:</strong>
  <%= @company.LinkedIn_URL %>
</p>

<p>
  <strong>Google a id:</strong>
  <%= @company.Google_A_ID %>
</p>

<p>
  <strong>Instagram url:</strong>
  <%= @company.Instagram_URL %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @company.Twitter_URL %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/image_assets/_form.html.erb
<%= form_with(model: image_asset, local: true) do |form| %>
  <% if image_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_asset.errors.count, "error") %> prohibited this image_asset from being saved:</h2>

      <ul>
        <% image_asset.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :approval %>
    <%= form.text_field :approval %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :uploads %>
    <%= form.file_field :uploads, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/image_assets/edit.html.erb
<h1>Editing Image Asset</h1>

<%= render 'form', image_asset: @image_asset %>

<%= link_to 'Show', @image_asset %> |
<%= link_to 'Back', image_assets_path %>

app/views/image_assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Assets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Approval</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_assets.each do |image_asset| %>
      <tr>
        <td><%= image_asset.name %></td>
        <td><%= image_asset.description %></td>
        <td><%= image_asset.approval %></td>
        <td><%= image_asset.category %></td>
        <td><%= image_asset.uploads %></td>
        <td><%= link_to 'Show', image_asset %></td>
        <td><%= link_to 'Edit', edit_image_asset_path(image_asset) %></td>
        <td><%= link_to 'Destroy', image_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Asset', new_image_asset_path %>

app/views/image_assets/new.html.erb
<h1>New Image Asset</h1>

<%= render 'form', image_asset: @image_asset %>

<%= link_to 'Back', image_assets_path %>

app/views/image_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image_asset.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image_asset.description %>
</p>

<p>
  <strong>Approval:</strong>
  <%= @image_asset.approval %>
</p>

<p>
  <strong>Category:</strong>
  <%= @image_asset.category %>
</p>

<% if @image_asset.uploads.attached? %>
<p>
  <strong>Images:</strong>
  <br>
  <% @image_asset.uploads.each do |image| %>
    <%= image_tag(image) %>
  <% end %>
</p>
<% end %>

<%= link_to 'Edit', edit_image_asset_path(@image_asset) %> |
<%= link_to 'Back', image_assets_path %>

app/views/layouts/_footer.html.erb
<footer class="sticky-bottom">
<div class="container-fluid">
<div class="row">
<div class="col-md-3 col-sm-6 col-xs-12">

<h3>About</h3>
<p>Your about information goes here</p>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
<ul>
<h3>Home</h3>

<li class="mt-2"><a href="#">Why W3Hubs?</a></li>
<li><a href="#">who are we?</a></li>
<li><a href="#">Why us?</a></li>
</ul>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
<ul>
<h3>Links</h3>

<li class="mt-2"><a href="#">Link1</a></li>
<li><a href="#">Link2</a></li>
<li><a href="#">Link3</a></li>
</ul>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">

<h3>Address</h3>
<p>15 Sutor Road, <br>
Decatur, <br>GA 30030,US</p>
</div>
</div>
<div class="icon">
  <a href="https://www.facebook.com/w3hubs.com2018/" target="_blank"><i class="fa fa-facebook-square"></i></a>
  <a href="https://tr.pinterest.com/w3hubs/" target="_blank"><i class="fa fa-pinterest"></i></a>
  <a href="https://www.reddit.com/user/w3hubs18" target="_blank"><i class="fa fa-reddit"></i></a>
  <a href="https://twitter.com/w3hubs" target="_blank"><i class="fa fa-twitter"></i></a>
</div>
</footer>
<div class="copyright">

app/views/layouts/_header.html.erb
<!-- Dummy Navigation to be worked in later -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="/">
    <img src="https://rootedweb.com/wp-content/uploads/2019/03/RootedWeb_logo-REV_1.png" alt="logo" style="width:40px;">
  </a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/companies">Companies</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/image_assets">Images</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/tags">Tags</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <title>RootedWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Bootstrap, Datatables CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <!-- Boostrap(3), Datatables, Font Awesome JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    <script src="https://kit.fontawesome.com/3ed505ad36.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
    <%= render "layouts/footer" %>
</html>

app/views/pages/index.html.erb
<!-- Coding snippet for devise login -->
<p class="navbar-text float-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<p>blah</p>
<p>blah</p>
<p>blah</p>
<p>blah</p>
<p>blah</p>
<p>blah</p>
<p>blah</p>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.slug %></td>
        <td><%= tag.category %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tag.slug %>
</p>

<p>
  <strong>Category:</strong>
  <%= @tag.category %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>